### PR TITLE
Add checkbox to windows

### PR DESCRIPTION
**Pull request by Phillips126**
I'm quite new to Nim and GUI development in general (mostly a web dev), but I really love working with NiGui and would like to contribute.  I don't know if you are willing to break parity between Win32 and GTK3 (I only work on Windows), but I added some simple checkboxes to NiGui for an application I am working on.

I used your existing Button code as a jumping off point so the code is quite identical.  I'm sure I could add a "button type" feature into the existing button code, but for now checkboxes are a separate entity.  I also added a "getState" method to check on the state of the checkbox:   `myCheckbox.getState()` will return a 0 (BST_UNCHECKED) or 1 (BST_CHECKED).

I hope this can help improve this awesome GUI :)
So here goes my first ever pull request!

### CODE REVIEW

**Comment by trustable-code** [comment]
Thank you and congrats to your first PR :). I will review it the next days.

**Comment by trustable-code** [comment]
See also: https://github.com/trustable-code/NiGui/pull/17

**Comment by Phillips126** [comment]
From a quick read through his PR, it does appear to be a better implementation as I don't have any events, etc.  I'd suggest we use the PR citycide has proposed.  I'm also currently working on implementing the combobox/dropdown feature that I hope to submit soon.

**Comment by trustable-code** [comment]
I'm finally :)
I have extended your implementation in https://github.com/trustable-code/NiGui/commit/9d9babe7491f791545ddb7730a573e9b21cd3fa6.
Now it works very well for me (Gtk and Windows).

**Comment by Phillips126** [comment]
Excellent work, thank you again for NiGui :)

**Pull request merged**
