### PR TITLE
Allow cross-compilation for Windows (on Linux)

### PR DESCRIPTION
**Pull request by ukoloff**
Quick-n-dirty hack to allow cross-compilation of NiGui apps [using mingw][cross]. 

It fails saying file `...\nigui-0.2.4\nigui\private\windows\manifest_x64.res` not found. Note backslashes in path. 

I believe this is error of Nim itself, but not sure. Any way it can be easily fixed by replacing all `\` to `/`. This works on Windows too.

[cross]: https://nim-lang.org/docs/nimc.html#cross-compilation-for-windows

### CODE REVIEW

**Comment by trustable-code** [comment]
Can you explain how to reproduce the problem with the backslashes?
I installed mingw-w64-gcc under Arch Linux, compiled a NiGui program using `nim c -d:mingw -d:release` and run it under a Windows VM. I don't see any problem.

Nim Compiler Version 1.2.6 [Linux: amd64]

**Comment by ukoloff** [comment]
Well, I use Ubuntu 18.04.5 LTS. I installed choosenim and nim 1.2.6 [Linux: amd64].

Command `nim c -d:mingw example_01_basic_app` gives error:
```
x86_64-w64-mingw32-gcc: error: \home\stas\.nimble\pkgs\nigui-0.2.4\nigui\private\windows\manifest_x64.res: No such file or directory
Error: execution of an external program failed: '/usr/bin/x86_64-w64-mingw32-gcc   -o /home/stas/dev/tmp/nim/nigui/win/example_01_basic_app.exe  '\home\stas\.nimble\pkgs\nigui-0.2.4\nigui\private\windows\manifest_x64.res'
```

Then I copied failed command, replaced `\` with `/`, it compiles and produces working Windows executable.

Command `nim c -d:mingw --cpu:i386 example_01_basic_app` does the same with `manifest_x64.res` replaced with `manifest_x86.res`.

**Comment by ukoloff** [comment]
The error can be reproduced in GitHub Actions too:

https://github.com/ukoloff/NiGui/runs/1067783049?check_suite_focus=true#step:10:68

**Comment by trustable-code** [comment]
OK, it seems to be a problem under Ubuntu LTS but not under Arch Linux.

**Pull request merged**
