### PR TITLE
Add CI testing workflow

### PR DESCRIPTION
**Pull request by jiro4989**

### CODE REVIEW

**Comment by trustable-code** [comment]
works, thanks :)

**Comment by trustable-code** [comment]
@jiro4989 The CI sometimes fails and I don't know why. Can you please take a look on the failed tests on https://github.com/trustable-code/NiGui/actions  ?

**Comment by jiro4989** [comment]
@trustable-code Oh, sorry.
Sometimes will faile to install nim when use caching of nimble.
Need skiping use cache on windows.

> https://github.com/jiro4989/setup-nim-action#cache-usage

**Comment by jiro4989** [comment]
wait a minute.
I will create a hotfix PR.

**Comment by jiro4989** [comment]
I created a PR #104 
Please review 🙏

**Pull request merged**
